### ISSUE TITLE
Initial Funds

### ISSUE THREAD

**Issue by frankieorabona** [lvgamedev/simairport-i18n#165]
"INITIAL FUNDS" the option that we read when starting a new game is not translated into any language, nor is it present in any file (UI, Triggers, etc)
Same thing for AIRLINE OPTIONS
If I press ESC in the game, I can't translate OPTIONS and QUIT in the menu

**Comment by joscha999** [comment]
Thanks for the report! We just fixed those occasions, they're now all translatable.
