### ISSUE TITLE
German Issue, and Game Issue

### ISSUE THREAD

**Issue by 19Topgun93** [lvgamedev/simairport-i18n#35]
Hello Girls and Guys,

I have a Translate Issue for you. At the Gate the Gate desk had to be assign to the Gate. In german that means: Mindestens ein zugewiesener Gate-Schalter erforderlich. Not: Mindestens ein zugewiesener Check-In-Schalter erforderlich.

And one another. My Airport have 4 S, 4 L, 7 XL Gates. And now when I have laggs when I build something :(

But your game is very cool :)

Best Greets

Lukas

**Comment by ValoisMedoc** [comment]
OK for the translation.
Building lagg same for everyone BUT it is really much better now! Good work so far.

**Comment by lvgamedev** [comment]
Thanks, just updated this
